# workflow name
name: Generate release-artifacts

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

# workflow tasks
jobs:
  release-matrix:
    name: Release Go binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows, freebsd]
        goarch: [amd64, 386, arm64, arm]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Build
        run: go build -o masterclass-dl-${{ matrix.goos }}-${{ matrix.goarch }}${{ runner.os == 'Windows' ? '.exe' : '' }} .
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./masterclass-dl-${{ matrix.goos }}-${{ matrix.goarch }}${{ runner.os == 'Windows' ? '.exe' : '' }}
          asset_name: masterclass-dl-${{ matrix.goos }}-${{ matrix.goarch }}${{ runner.os == 'Windows' ? '.exe' : '' }}
          asset_content_type: application/octet-stream